version: "3.8"

volumes:

  apldashboard-data:
    driver: local

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: apl-dashboard
    ports:
      - 7000:3000
    volumes:
      - apldashboard-data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dproxy-beapl
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped